brew 'direnv'
brew 'elasticsearch'
brew 'fish'
brew 'git'
brew 'imagemagick'
# brew 'node'
brew 'phantomjs'
brew 'redis'
# brew 'yarn'
# brew 'mkcert'

tap 'caskroom/cask'
tap 'caskroom/homebrew-versions'

cask 'google-chrome'
cask 'postico'
cask 'sketch'
cask 'slack'
cask 'insomnia'
cask 'ship'
